### ISSUE TITLE
feat: make "contribute here" button more attractive.

### ISSUE THREAD

**Issue by codingninja11** [codingninja11/payment_gateway_grip#1]
Add some pretty hovering effect so that it attracts the user.

![image](https://user-images.githubusercontent.com/64359203/135496790-5a96c9b7-8e50-4646-b5d0-292410cbd159.png)

**Comment by anushruti11** [comment]
I would like to work on this issue.

**Comment by codingninja11** [comment]
> I would like to work on this issue.
> 
> 

Go for it
